name: CI

on:
    push:
    pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    tests:
        strategy:
            matrix:
                python_version: ["3.7", "3.9", "3.10"]
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Choose Python version ${{ matrix.python_version }}
              uses: actions/setup-python@v4
              with:
                python-version: '${{ matrix.python_version }}'
            - name: install tox
              run: python3 -m pip install tox
            - uses: actions/checkout@v3
            - name: run tox
              run: tox -e 'py${{ matrix.python_version }}'
            - name: submit code coverage
              uses: codecov/codecov-action@v3
    additional:
        strategy:
            matrix:
                envs: ["numba_coverage", "docs-check"]
        runs-on: ubuntu-latest
        steps:
            - name: 'Choose Python version 3.10'
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: install tox
              run: python3 -m pip install tox
            - uses: actions/checkout@v3
            - name: 'run tox for environment ${{ matrix.envs }}'
              run: tox -e '${{ matrix.envs }}'
            - name: submit code coverage
              uses: codecov/codecov-action@v3
